# Different JSON orient

| Orient    | Typical usage                      |
| --------- | ---------------------------------- |
| `records` | APIs / REST                        |
| `split`   | efficient DataFrame reconstruction |
| `columns` | default pandas format              |
| `table`   | standardized exchange              |
| `values`  | matrix-like data                   |

In [1]:
import pandas as pd

In [ ]:
try:
    # Load the JSON with orient specified
    df = pd.read_json("dhs_report_reformatted.json",
                      orient = 'split')
    
    # Plot total population in shelters over time
    df["date_of_census"] = pd.to_datetime(df["date_of_census"])
    df.plot(x="date_of_census", 
            y="total_individuals_in_shelter")
    plt.show()
    
except ValueError:
    print("pandas could not parse the JSON.")

In [2]:
df = pd.read_json('https://api.github.com/events?utm_source=chatgpt.com')

In [3]:
df.head()

,id,type,actor,repo,payload,public,created_at,org
0,11941794399,PushEvent,"{'id': 279672670, 'login': 'gnabbhobech84', 'd...","{'id': 1235899636, 'name': 'gnabbhobech84/mfka...","{'repository_id': 1235899636, 'push_id': 34232...",True,2026-05-16 12:32:11+00:00,NaN
1,11941794194,PushEvent,"{'id': 248741150, 'login': 'Atharva-Shimpi', '...","{'id': 1128341045, 'name': 'Atharva-Shimpi/Che...","{'repository_id': 1128341045, 'push_id': 34232...",True,2026-05-16 12:32:10+00:00,NaN
2,11941794534,PushEvent,"{'id': 519108, 'login': 'twardoch', 'display_l...","{'id': 929609324, 'name': 'twardoch/twat-audio...","{'repository_id': 929609324, 'push_id': 342323...",True,2026-05-16 12:32:11+00:00,NaN
3,11941794391,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 289099942, 'name': 'FeMaffezzolli/femaf...","{'repository_id': 289099942, 'push_id': 342323...",True,2026-05-16 12:32:11+00:00,NaN
4,11941794533,PushEvent,"{'id': 275436210, 'login': 'estate49code-cpu',...","{'id': 1208596335, 'name': 'estate49code-cpu/e...","{'repository_id': 1208596335, 'push_id': 34232...",True,2026-05-16 12:32:11+00:00,NaN

In [11]:
df1 = pd.read_json('https://api.github.com/events?utm_source=chatgpt.com', orient='values')
df1.head()

,id,type,actor,repo,payload,public,created_at,org
0,11941935772,PushEvent,"{'id': 72733847, 'login': 'evgeniy-baker', 'di...","{'id': 1209704187, 'name': 'evgeniy-baker/Todo...","{'repository_id': 1209704187, 'push_id': 34232...",True,2026-05-16 12:38:51+00:00,NaN
1,11941935729,PushEvent,"{'id': 241027756, 'login': 'iotdepartment', 'd...","{'id': 1087331674, 'name': 'iotdepartment/PuEx...","{'repository_id': 1087331674, 'push_id': 34232...",True,2026-05-16 12:38:51+00:00,NaN
2,11941935961,CreateEvent,"{'id': 166895733, 'login': 'swa-runner-app[bot...","{'id': 1240670015, 'name': 'static-web-apps-te...","{'ref': 'prBranch', 'ref_type': 'branch', 'ful...",True,2026-05-16 12:38:52+00:00,"{'id': 96167003, 'login': 'static-web-apps-tes..."
3,11941935634,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 777190929, 'name': '4k5u/test', 'url': ...","{'repository_id': 777190929, 'push_id': 342325...",True,2026-05-16 12:38:50+00:00,"{'id': 164875060, 'login': '4k5u', 'gravatar_i..."
4,11941935637,PushEvent,"{'id': 242868331, 'login': 'Virineya-I', 'disp...","{'id': 1240608513, 'name': 'Virineya-I/Social-...","{'repository_id': 1240608513, 'push_id': 34232...",True,2026-05-16 12:38:50+00:00,NaN

Very important limitation

json_normalize() handles nested DICTS beautifully.

In [13]:
import requests


data = requests.get(
    "https://api.github.com/events"
).json()

df2 = pd.json_normalize(data)
df2.head()

,id,type,public,created_at,actor.id,actor.login,actor.display_login,actor.gravatar_id,actor.url,actor.avatar_url,...,org.id,org.login,org.gravatar_id,org.url,org.avatar_url,payload.ref_type,payload.full_ref,payload.master_branch,payload.description,payload.pusher_type
0,11941952558,PushEvent,True,2026-05-16T12:39:38Z,35573323,JoWe112,JoWe112,,https://api.github.com/users/JoWe112,https://avatars.githubusercontent.com/u/35573323?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11941952663,PushEvent,True,2026-05-16T12:39:38Z,168531570,Shalmankursheeth,Shalmankursheeth,,https://api.github.com/users/Shalmankursheeth,https://avatars.githubusercontent.com/u/168531...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11941952481,PushEvent,True,2026-05-16T12:39:38Z,614115,goldyfruit,goldyfruit,,https://api.github.com/users/goldyfruit,https://avatars.githubusercontent.com/u/614115?,...,275374493.0,thalovant,,https://api.github.com/orgs/thalovant,https://avatars.githubusercontent.com/u/275374...,NaN,NaN,NaN,NaN,NaN
3,11941952470,PushEvent,True,2026-05-16T12:39:38Z,114727033,kantilalnjadhav,kantilalnjadhav,,https://api.github.com/users/kantilalnjadhav,https://avatars.githubusercontent.com/u/114727...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11941952465,PushEvent,True,2026-05-16T12:39:38Z,2299951,emilyalbini,emilyalbini,,https://api.github.com/users/emilyalbini,https://avatars.githubusercontent.com/u/2299951?,...,5430905.0,rust-lang,,https://api.github.com/orgs/rust-lang,https://avatars.githubusercontent.com/u/5430905?,NaN,NaN,NaN,NaN,NaN

In [19]:
api_url =  "https://api.github.com/events"

# Get data about NYC cafes from the Yelp API
response = requests.get(api_url, 
                headers=headers, 
                params=params)

# Extract JSON data from the response
data = response.json()

# Load data to a dataframe
cafes = pd.DataFrame(data["businesses"])

# View the data's dtypes
print(cafes.dtypes)

list

In [ ]:
# Create dictionary to query API for cafes in NYC
parameters = {'term':'cafe','location':'NYC'}

# Query the Yelp API with headers and params set
response = requests.get(api_url,
                headers= headers,
                params = parameters)

# Extract JSON data from response
data = response.json()

# Load "businesses" values to a dataframe and print head
cafes = pd.DataFrame(data["businesses"])
print(cafes.head())

In [ ]:
# Create dictionary that passes Authorization and key string
headers = {"Authorization": "Bearer {}".format(api_key)}

# Query the Yelp API with headers and params set
response = requests.get(api_url, headers=headers, params=params)



# Extract JSON data from response
data = response.json()

# Load "businesses" values to a dataframe and print names
cafes = pd.DataFrame(data["businesses"])
print(cafes.name)

In [ ]:
# Add an offset parameter to get cafes 51-100
params = {"term": "cafe", 
          "location": "NYC",
          "sort_by": "rating", 
          "limit": 50,
          "offset": 50}

result = requests.get(api_url, headers=headers, params=params)
next_50_cafes = json_normalize(result.json()["businesses"])

# Concatenate the results, setting ignore_index to renumber rows
cafes = pd.concat([top_50_cafes,next_50_cafes])

# Print shape of cafes
cafes.shape